### ISSUE TITLE
Crash when Loading Saved Game

### ISSUE THREAD

**Issue by ixPost** [immibis/colobot#4]
I was testing a program on Analysis and I was afraid the wasps would destroy the defense tower so I saved the game. I was holding a titanium cube at the moment at least I think so and my OS is Ubuntu 21.04. Crash message: Unhandled exception occurred!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You are running official 0.1.12-alpha build.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=6 rank=2
==============================

Sorry for inconvenience!

'|' Application: Zenity

**Comment by immibis** [comment]
you are in the wrong place, how did you find this? Try clicking on that big link you posted

**Comment by ixPost** [comment]
It leads to the Colobot issues page on GitHub.

**Comment by immibis** [comment]
yeah so why don't you post your issue there? Are you running my customized version of colobot somehow?

**Comment by ixPost** [comment]
*H💩o💩w d💩a💩r💩e
y💩o💩u💩💚🐛🦇☹!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*
